package GeDL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ObservationType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ObservationType() {
    super(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x56a0a8571da38eb1L, "ObservationType", "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6242174175648386737");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Measurement_0 = new EnumerationDescriptor.MemberDescriptor("Measurement", "measurement", 0x56a0a8571da38eb2L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6242174175648386738");
  private final EnumerationDescriptor.MemberDescriptor myMember_Category_0 = new EnumerationDescriptor.MemberDescriptor("Category", "category", 0x56a0a8571da38eb3L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6242174175648386739");
  private final EnumerationDescriptor.MemberDescriptor myMember_Count_0 = new EnumerationDescriptor.MemberDescriptor("Count", "count", 0x56a0a8571da38eb6L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6242174175648386742");
  private final EnumerationDescriptor.MemberDescriptor myMember_Truth_0 = new EnumerationDescriptor.MemberDescriptor("Truth", "truth", 0x56a0a8571da38ebaL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6242174175648386746");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x56a0a8571da38eb1L, 0x56a0a8571da38eb2L, 0x56a0a8571da38eb3L, 0x56a0a8571da38eb6L, 0x56a0a8571da38ebaL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Measurement_0, myMember_Category_0, myMember_Count_0, myMember_Truth_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Measurement_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Measurement":
        return myMember_Measurement_0;
      case "Category":
        return myMember_Category_0;
      case "Count":
        return myMember_Count_0;
      case "Truth":
        return myMember_Truth_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
