package GeDL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SpatialRelation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SpatialRelation() {
    super(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x562897dc3cfb235cL, "SpatialRelation", "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6208379058501919580");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_single_0 = new EnumerationDescriptor.MemberDescriptor("single", "single", 0x562897dc3cfb235dL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6208379058501919581");
  private final EnumerationDescriptor.MemberDescriptor myMember_cloud_0 = new EnumerationDescriptor.MemberDescriptor("cloud", "cloud", 0x562897dc3cfb235eL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6208379058501919582");
  private final EnumerationDescriptor.MemberDescriptor myMember_specks_0 = new EnumerationDescriptor.MemberDescriptor("specks", "specks", 0x562897dc3cfb235fL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6208379058501919583");
  private final EnumerationDescriptor.MemberDescriptor myMember_all_0 = new EnumerationDescriptor.MemberDescriptor("all", "all", 0x562897dc3cfb2360L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/6208379058501919584");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x562897dc3cfb235cL, 0x562897dc3cfb235dL, 0x562897dc3cfb235eL, 0x562897dc3cfb235fL, 0x562897dc3cfb2360L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_single_0, myMember_cloud_0, myMember_specks_0, myMember_all_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_single_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "single":
        return myMember_single_0;
      case "cloud":
        return myMember_cloud_0;
      case "specks":
        return myMember_specks_0;
      case "all":
        return myMember_all_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
