package GeDL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DurationUnit extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DurationUnit() {
    super(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x61e69d1f3f9cf5f1L, "DurationUnit", "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258865");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_second_0 = new EnumerationDescriptor.MemberDescriptor("second", "second", 0x61e69d1f3f9cf5f3L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258867");
  private final EnumerationDescriptor.MemberDescriptor myMember_minunte_0 = new EnumerationDescriptor.MemberDescriptor("minunte", "minunte", 0x61e69d1f3f9cf5f6L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258870");
  private final EnumerationDescriptor.MemberDescriptor myMember_hour_0 = new EnumerationDescriptor.MemberDescriptor("hour", "hour", 0x61e69d1f3f9cf5f2L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258866");
  private final EnumerationDescriptor.MemberDescriptor myMember_day_0 = new EnumerationDescriptor.MemberDescriptor("day", "day", 0x61e69d1f3f9cf5faL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258874");
  private final EnumerationDescriptor.MemberDescriptor myMember_week_0 = new EnumerationDescriptor.MemberDescriptor("week", "week", 0x61e69d1f3f9cf5ffL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258879");
  private final EnumerationDescriptor.MemberDescriptor myMember_month_0 = new EnumerationDescriptor.MemberDescriptor("month", "month", 0x61e69d1f3f9cf605L, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258885");
  private final EnumerationDescriptor.MemberDescriptor myMember_year_0 = new EnumerationDescriptor.MemberDescriptor("year", "year", 0x61e69d1f3f9cf60cL, "r:0acff501-71d6-4896-b79d-b8d89273d027(GeDL.structure)/7054498623859258892");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x61e69d1f3f9cf5f1L, 0x61e69d1f3f9cf5f3L, 0x61e69d1f3f9cf5f6L, 0x61e69d1f3f9cf5f2L, 0x61e69d1f3f9cf5faL, 0x61e69d1f3f9cf5ffL, 0x61e69d1f3f9cf605L, 0x61e69d1f3f9cf60cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_second_0, myMember_minunte_0, myMember_hour_0, myMember_day_0, myMember_week_0, myMember_month_0, myMember_year_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "second":
        return myMember_second_0;
      case "minunte":
        return myMember_minunte_0;
      case "hour":
        return myMember_hour_0;
      case "day":
        return myMember_day_0;
      case "week":
        return myMember_week_0;
      case "month":
        return myMember_month_0;
      case "year":
        return myMember_year_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
