package GeDL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class EventParameter_Constraints extends BaseConstraintsDescriptor {
  public EventParameter_Constraints() {
    super(CONCEPTS.EventParameter$sK);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EventParameter$sK = MetaAdapterFactory.getConcept(0x35b540ea51fc45c2L, 0x8fb01d48ca99c3dbL, 0x24b3732dd914c0f9L, "GeDL.structure.EventParameter");
  }
}
