package GeDL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SpatialRelation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SpatialRelation() {
    super(0x5194ff76e65f4a57L, 0xba19488ab6bc5674L, 0x36a0243b46771f0fL, "SpatialRelation", "r:381ef4cc-a346-4256-af1f-72c1e3a69e63(GeDL.structure)/3936185911325695759");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_single_0 = new EnumerationDescriptor.MemberDescriptor("single", "single", 0x36a0243b46771f10L, "r:381ef4cc-a346-4256-af1f-72c1e3a69e63(GeDL.structure)/3936185911325695760");
  private final EnumerationDescriptor.MemberDescriptor myMember_cloud_0 = new EnumerationDescriptor.MemberDescriptor("cloud", "cloud", 0x36a0243b46771f11L, "r:381ef4cc-a346-4256-af1f-72c1e3a69e63(GeDL.structure)/3936185911325695761");
  private final EnumerationDescriptor.MemberDescriptor myMember_specks_0 = new EnumerationDescriptor.MemberDescriptor("specks", "specks", 0x36a0243b46771f14L, "r:381ef4cc-a346-4256-af1f-72c1e3a69e63(GeDL.structure)/3936185911325695764");
  private final EnumerationDescriptor.MemberDescriptor myMember_all_0 = new EnumerationDescriptor.MemberDescriptor("all", "all", 0x36a0243b46771f18L, "r:381ef4cc-a346-4256-af1f-72c1e3a69e63(GeDL.structure)/3936185911325695768");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5194ff76e65f4a57L, 0xba19488ab6bc5674L, 0x36a0243b46771f0fL, 0x36a0243b46771f10L, 0x36a0243b46771f11L, 0x36a0243b46771f14L, 0x36a0243b46771f18L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_single_0, myMember_cloud_0, myMember_specks_0, myMember_all_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_single_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "single":
        return myMember_single_0;
      case "cloud":
        return myMember_cloud_0;
      case "specks":
        return myMember_specks_0;
      case "all":
        return myMember_all_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
